### ISSUE TITLE
Docs enhancements

### ISSUE THREAD

**Issue by vadimkorr** [vadimkorr/svelte-carousel#48]
- [x] Fix typos (#48)
- [x] Describe adding the package to sveltekit project
- [x] Add anchors to demo site (#48)
- [x] Add args to goTo description `goTo (pageIndex, options) => Promise<void>`
- [x] Add paused indicator and prop (#62)
- [x] Add link to Svelte REPL 
- [x] Update license
- [ ] Add id of already shown page ids to images array on lazy loading (feature)
- [x] Add description to demo of how to pause
- [x] Fix touch event warnings (#57)
- [x] Move link icon to top a bit
